name = "mavlink_common_v2"
description = "MAVLink v2-- Micro Air Vehicle Message Marshalling Library."
version = "1.0.0"

authors = ["Fil Andrii", "Max Reznik"]
maintainers = ["Fil Andrii <root.fi36@gmail.com>", "Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["python36", "reznikmm"]
licenses = "MIT"
website = "https://mavlink.io"
tags = ["embedded", "network", "drone"]

project-files = ["gnat/mavlink_common_v2.gpr"]

[build-switches]
"*".style_checks = ["-gnatyN"]
"*".ada_version = "Ada2022"

[[depends-on]]
mavlink_shared = "^1.0"

[[pins]]
mavlink_shared = { url='https://github.com/reznikmm/mavlink_shared' }
