name = "mavlink_common"
description = "MAVLink -- Micro Air Vehicle Message Marshalling Library."
version = "1.0.3"

authors = ["Fil Andrii"]
maintainers = ["Fil Andrii <root.fi36@gmail.com>", "Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["python36", "reznikmm"]
licenses = "MIT"
website = "https://mavlink.io"
tags = ["embedded", "network", "drone"]

project-files = ["gnat/mavlink_common.gpr", "gnat/mavlink_common_limited.gpr"]

auto-gpr-with = false

[build-switches]
"*".style_checks = ["-gnatyN"]
