-------------------------------------------
--  DO NOT EDIT. This file is generated. --
-------------------------------------------

--  Copyright Fil Andrii root.fi36@gmail.com 2022-2025

--  Status generated by radio and injected into MAVLink stream.

pragma Ada_2022;

package MAVLink.V1.Common.Radio_Statuses is

   pragma Pure;

   Radio_Status_Len : constant Interfaces.Unsigned_8 := 9;

   type Radio_Status is record
      Rssi     : Interfaces.Unsigned_8 :=
        Interfaces.Unsigned_8'Last;
      --  Local (message sender) received signal strength indication in
      --  device-dependent units/scale. Values: [0-254], UINT8_MAX:
      --  invalid/unknown.
      Remrssi  : Interfaces.Unsigned_8 :=
        Interfaces.Unsigned_8'Last;
      --  Remote (message receiver) signal strength indication in
      --  device-dependent units/scale. Values: [0-254], UINT8_MAX:
      --  invalid/unknown.
      Txbuf    : Interfaces.Unsigned_8;
      --  Units: [%]
      --  Remaining free transmitter buffer space.
      Noise    : Interfaces.Unsigned_8 :=
        Interfaces.Unsigned_8'Last;
      --  Local background noise level. These are device dependent RSSI values
      --  (scale as approx 2x dB on SiK radios). Values: [0-254], UINT8_MAX:
      --  invalid/unknown.
      Remnoise : Interfaces.Unsigned_8 :=
        Interfaces.Unsigned_8'Last;
      --  Remote background noise level. These are device dependent RSSI
      --  values (scale as approx 2x dB on SiK radios). Values: [0-254],
      --  UINT8_MAX: invalid/unknown.
      Rxerrors : Interfaces.Unsigned_16;
      --  Count of radio packet receive errors (since boot).
      Fixed    : Interfaces.Unsigned_16;
      --  Count of error corrected radio packets (since boot).
   end record;

   for Radio_Status use record
      Rxerrors at 0 range 0 .. 15;
      Fixed    at 2 range 0 .. 15;
      Rssi     at 4 range 0 .. 7;
      Remrssi  at 5 range 0 .. 7;
      Txbuf    at 6 range 0 .. 7;
      Noise    at 7 range 0 .. 7;
      Remnoise at 8 range 0 .. 7;
   end record;

   procedure Encode
     (Message : Radio_Status;
      Connect : in out MAVLink.V1.Out_Connection;
      Buffer  : out Data_Buffer;
      Last    : out Positive);
   --  Put the message in the buffer ready for send

   procedure Encode
     (Message : Radio_Status;
      Connect : in out MAVLink.V1.Connection;
      Buffer  : out Data_Buffer;
      Last    : out Positive);

   procedure Decode
     (Message   : out Radio_Status;
      Connect   : in out MAVLink.V1.Connection;
      CRC_Valid : out Boolean);
   --  Get the message from the Connect if x25crc is valid and
   --  set CRC_Valid to True.
   --  Won't read data from the Connect if x25crc is False.
   --  For v1: Won't read data from the Connect if message length mismatch
   --    and set CRC_Valid to False in this case.
   --  For v2: Truncate the extension fields.

   procedure Decode
     (Message : out Radio_Status;
      Connect : MAVLink.V1.Connection);
   --  Get the message from the Connect.
   --  For v1: May raise exception when message length mismatch
   --  For v2: Truncate the extension fields.

   procedure Decode
     (Message   : out Radio_Status;
      Connect   : in out MAVLink.V1.In_Connection;
      CRC_Valid : out Boolean);
   --  Get the message from the Connect if x25crc is valid and
   --  set CRC_Valid to True.
   --  Won't read data from the Connect if x25crc is False.
   --  For v1: Won't read data from the Connect if message length mismatch
   --    and set CRC_Valid to False in this case.
   --  For v2: Truncate the extension fields.

   procedure Decode
     (Message : out Radio_Status;
      Connect : MAVLink.V1.In_Connection);
   --  Get the message from the Connect.
   --  For v1: May raise an exception when message length mismatch
   --  For v2: Truncate the extension fields.

   function Check_CRC
     (Connect : in out MAVLink.V1.Connection)
      return Boolean with Inline;
   --  Returns True if CRC is valid

   function Check_CRC
     (Connect : in out MAVLink.V1.In_Connection)
      return Boolean with Inline;
   --  Returns True if CRC is valid

end MAVLink.V1.Common.Radio_Statuses;
